services:
  app:
    build: .
    ports:
      - "${APP_PORT}:8001"
    environment:
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - NATS_URL=nats://host.docker.internal:4222
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - qdrant
    networks:
      - gony-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "${QDRANT_PORT}:${QDRANT_PORT}"
      - "${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - gony-network

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - gony-network
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  gony-network:
    driver: bridge

volumes:
  qdrant_storage:
  cassandra_data:
