[project]
name = "gony-agentic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno[qdrant]>=2.4.8",
    "alembic>=1.18.3",
    "fastapi>=0.128.2",
    "mcp>=1.26.0",
    "nats-py>=2.13.1",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "psycopg[binary]>=3.2.4",
    "sqlalchemy>=2.0.46",
    "uvicorn>=0.40.0",
    "fastmcp>=2.14.5",
    "cassandra-driver>=3.29.0",
    "cqlengine>=0.21.0",
]
